// oxlint-disable max-lines
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              status: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
            deviceInfo?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                accessToken: string;
                refreshToken: string;
              };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              errors: {
                id?: string;
                links?: {
                  about?: string;
                  type?: string;
                };
                status: string;
                code?: string;
                title: string;
                detail?: string;
                source?: {
                  pointer?: string;
                  parameter?: string;
                  header?: string;
                };
                meta?: {
                  [key: string]: unknown;
                };
              }[];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            refreshToken: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                accessToken: string;
                refreshToken: string;
              };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              errors: {
                id?: string;
                links?: {
                  about?: string;
                  type?: string;
                };
                status: string;
                code?: string;
                title: string;
                detail?: string;
                source?: {
                  pointer?: string;
                  parameter?: string;
                  header?: string;
                };
                meta?: {
                  [key: string]: unknown;
                };
              }[];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            refreshToken: string;
            /** @default false */
            allDevices?: boolean;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                success: boolean;
                message: string;
              };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              errors: {
                id?: string;
                links?: {
                  about?: string;
                  type?: string;
                };
                status: string;
                code?: string;
                title: string;
                detail?: string;
                source?: {
                  pointer?: string;
                  parameter?: string;
                  header?: string;
                };
                meta?: {
                  [key: string]: unknown;
                };
              }[];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                /** @enum {string} */
                type: "users";
                attributes: {
                  /** Format: email */
                  email: string;
                  firstName: string;
                  lastName: string;
                };
              }[];
              meta: {
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            data: {
              id?: string | null;
              attributes: {
                /** Format: email */
                email: string;
                firstName: string;
                lastName: string;
                password: string;
              };
            };
            meta?: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                /** @enum {string} */
                type: "users";
                attributes: {
                  /** Format: email */
                  email: string;
                  firstName: string;
                  lastName: string;
                };
              };
              meta?: {
                [key: string]: unknown;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                /** @enum {string} */
                type: "users";
                attributes: {
                  /** Format: email */
                  email: string;
                  firstName: string;
                  lastName: string;
                };
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                /** @enum {string} */
                type: "users";
                attributes: {
                  /** Format: email */
                  email: string;
                  firstName: string;
                  lastName: string;
                };
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              errors: {
                id?: string;
                links?: {
                  about?: string;
                  type?: string;
                };
                status: string;
                code?: string;
                title: string;
                detail?: string;
                source?: {
                  pointer?: string;
                  parameter?: string;
                  header?: string;
                };
                meta?: {
                  [key: string]: unknown;
                };
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {null} */
              data: null;
              meta?: {
                [key: string]: unknown;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              errors: {
                id?: string;
                links?: {
                  about?: string;
                  type?: string;
                };
                status: string;
                code?: string;
                title: string;
                detail?: string;
                source?: {
                  pointer?: string;
                  parameter?: string;
                  header?: string;
                };
                meta?: {
                  [key: string]: unknown;
                };
              }[];
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              errors: {
                id?: string;
                links?: {
                  about?: string;
                  type?: string;
                };
                status: string;
                code?: string;
                title: string;
                detail?: string;
                source?: {
                  pointer?: string;
                  parameter?: string;
                  header?: string;
                };
                meta?: {
                  [key: string]: unknown;
                };
              }[];
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            data: {
              id: string;
              /** @enum {string} */
              type: "users";
              attributes: {
                /** Format: email */
                email: string;
                firstName: string;
                lastName: string;
              };
            };
            meta?: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                /** @enum {string} */
                type: "users";
                attributes: {
                  /** Format: email */
                  email: string;
                  firstName: string;
                  lastName: string;
                };
              };
              meta?: {
                [key: string]: unknown;
              };
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              errors: {
                id?: string;
                links?: {
                  about?: string;
                  type?: string;
                };
                status: string;
                code?: string;
                title: string;
                detail?: string;
                source?: {
                  pointer?: string;
                  parameter?: string;
                  header?: string;
                };
                meta?: {
                  [key: string]: unknown;
                };
              }[];
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              errors: {
                id?: string;
                links?: {
                  about?: string;
                  type?: string;
                };
                status: string;
                code?: string;
                title: string;
                detail?: string;
                source?: {
                  pointer?: string;
                  parameter?: string;
                  header?: string;
                };
                meta?: {
                  [key: string]: unknown;
                };
              }[];
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/todos/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                /** @enum {string} */
                type: "todos";
                attributes: {
                  title: string;
                  description: string | null;
                  completed: boolean;
                  createdAt: string;
                  updatedAt: string;
                };
              }[];
              meta: {
                total: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            data: {
              id?: string | null;
              attributes: {
                title: string;
                description?: string | null;
                completed?: boolean;
              };
            };
            meta?: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                /** @enum {string} */
                type: "todos";
                attributes: {
                  title: string;
                  description: string | null;
                  completed: boolean;
                  createdAt: string;
                  updatedAt: string;
                };
              };
              meta?: {
                [key: string]: unknown;
              };
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/todos/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                /** @enum {string} */
                type: "todos";
                attributes: {
                  title: string;
                  description: string | null;
                  completed: boolean;
                  createdAt: string;
                  updatedAt: string;
                };
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              errors: {
                id?: string;
                links?: {
                  about?: string;
                  type?: string;
                };
                status: string;
                code?: string;
                title: string;
                detail?: string;
                source?: {
                  pointer?: string;
                  parameter?: string;
                  header?: string;
                };
                meta?: {
                  [key: string]: unknown;
                };
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {null} */
              data: null;
              meta?: {
                [key: string]: unknown;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              errors: {
                id?: string;
                links?: {
                  about?: string;
                  type?: string;
                };
                status: string;
                code?: string;
                title: string;
                detail?: string;
                source?: {
                  pointer?: string;
                  parameter?: string;
                  header?: string;
                };
                meta?: {
                  [key: string]: unknown;
                };
              }[];
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            data: {
              id: string;
              /** @enum {string} */
              type: "todos";
              attributes: {
                title: string;
                description: string | null;
                completed: boolean;
                createdAt: string;
                updatedAt: string;
              };
            };
            meta?: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                /** @enum {string} */
                type: "todos";
                attributes: {
                  title: string;
                  description: string | null;
                  completed: boolean;
                  createdAt: string;
                  updatedAt: string;
                };
              };
              meta?: {
                [key: string]: unknown;
              };
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              errors: {
                id?: string;
                links?: {
                  about?: string;
                  type?: string;
                };
                status: string;
                code?: string;
                title: string;
                detail?: string;
                source?: {
                  pointer?: string;
                  parameter?: string;
                  header?: string;
                };
                meta?: {
                  [key: string]: unknown;
                };
              }[];
            };
          };
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
